// create some array of object date here
const bioBlodDonner = [
  {
    id: 1,
    name: "asrafull",
    age: 26,
    bloodGroup: "A",
    address: "mirpur",
    phone: "016432735",
    lastDonad: 90,
    isMarriage: false,
    donatehistory: [
      {
        name: `munna`,
        name: `asik`,
        name: `rodri`,
      },
    ],
  },
  {
    id: 2,
    name: "nurjamall",
    age: 37,
    bloodGroup: "A+",
    address: "dinajpur",
    phone: "016432735",
    lastDonad: 60,
    isMarriage: true,
    donatehistory: [
      {
        name: `naan`,
        name: `asikan`,
        name: `cavin`,
      },
    ],
  },
  {
    id: 3,
    name: "asutos gosh",
    age: 30,
    bloodGroup: "AB+",
    address: "uttara",
    phone: "016432735",
    lastDonad: 120,
    isMarriage: false,
    donatehistory: [
      {
        name: `horyra`,
        name: `hasib`,
        name: `ibrahim`,
      },
    ],
  },
  {
    id: 4,
    name: "Mahdi",
    age: 45,
    bloodGroup: "AB-",
    address: "Mirpur",
    phone: "016432735",
    lastDonad: 90,
    isMarriage: true,
    donatehistory: [
      {
        name: `soyed`,
        name: `ripon`,
        name: `nazma`,
      },
    ],
  },
  {
    id: 5,
    name: "Uttam Roy",
    age: 40,
    bloodGroup: "A+",
    address: "Kuyakata",
    phone: "016432735",
    lastDonad: 100,
    isMarriage: false,
    donatehistory: [
      {
        name: `aklima`,
        name: `faruk`,
        name: `rokchana`,
      },
    ],
  },
  {
    id: 6,
    name: "jamal",
    age: 60,
    bloodGroup: "O-",
    address: "Uttara",
    phone: "016432735",
    lastDonad: 80,
    isMarriage: false,
    donatehistory: [
      {
        name: `kadir`,
        name: `saju`,
        name: `sahnewaz`,
      },
    ],
  },
  {
    id: 7,
    name: "raja",
    age: 30,
    bloodGroup: "O+",
    address: "Rangpur",
    phone: "016432735",
    lastDonad: 120,
    isMarriage: false,
    donatehistory: [
      {
        name: `kobir`,
        name: `rubna`,
        name: `jahed`,
      },
    ],
  },
  {
    id: 8,
    name: "azas",
    age: 24,
    bloodGroup: "O-",
    address: "chandpur",
    phone: "0164244455",
    lastDonad: 10,
    isMarriage: false,
    donatehistory: [
      {
        name: `samim`,
        name: `taslima`,
        name: `habu`,
      },
    ],
  },
  {
    id: 9,
    name: "rasel",
    age: 80,
    bloodGroup: "AB+",
    address: "rangpur",
    phone: "016432735",
    lastDonad: 160,
    isMarriage: false,
    donatehistory: [
      {
        name: `shanto`,
        name: `shakib`,
        name: `mahmud`,
      },
    ],
  },
  {
    id: 10,
    name: "ruhul",
    age: 40,
    bloodGroup: "O+",
    address: "rangpur",
    phone: "016332735",
    lastDonad: 120,
    isMarriage: false,
    donatehistory: [
      {
        name: `taskin`,
        name: `tonni`,
        name: `sagir`,
      },
    ],
  },
  {
    id: 11,
    name: "nuru",
    age: 17,
    bloodGroup: "A",
    address: "dhaka",
    phone: "016412735",
    lastDonad: 120,
    isMarriage: false,
    donatehistory: [
      {
        name: `nasir`,
        name: `alauddin`,
        name: `ruhul`,
      },
    ],
  },

  {
    id: 12,
    name: "mehedi",
    age: 20,
    bloodGroup: "A+",
    address: "mirpur",
    phone: "016422735",
    lastDonad: 97,
    isMarriage: false,
    donatehistory: [
      {
        name: `jangir`,
        name: `shajan`,
        name: `siam`,
      },
    ],
  },
  {
    id: 13,
    name: "rahul",
    age: 30,
    bloodGroup: "O+",
    address: "Uttara",
    phone: "016432735",
    lastDonad: 120,
    isMarriage: false,
    donatehistory: [
      {
        name: `ashraful`,
        name: `asika`,
        name: `rodri`,
      },
    ],
  },
  {
    id: 14,
    name: "jaber",
    age: 37,
    bloodGroup: "O-",
    address: "rangpur",
    phone: "013432735",
    lastDonad: 200,
    isMarriage: false,
    donatehistory: [
      {
        name: `jannat`,
        name: `tania`,
        name: `kaiuum`,
      },
    ],
  },
  {
    id: 15,
    name: "necer",
    age: 30,
    bloodGroup: "AB+",
    address: "rangpur",
    phone: "016432735",
    lastDonad: 120,
    isMarriage: false,
    donatehistory: [
      {
        name: `tankijna`,
        name: `helal`,
        name: `odin`,
      },
    ],
  },
  {
    id: 16,
    name: "sagor",
    age: 17,
    bloodGroup: "O+",
    address: "dhaka",
    phone: "010432735",
    lastDonad: 220,
    isMarriage: false,
    donatehistory: [
      {
        name: `bayezid`,
        name: `tanjil`,
        name: `rahman`,
      },
    ],
  },
  {
    id: 17,
    name: "rajjak",
    age: 30,
    bloodGroup: "A",
    address: "rangpur",
    phone: "016432735",
    lastDonad: 160,
    isMarriage: false,
    donatehistory: [
      {
        name: `abdul`,
        name: `riyad`,
        name: `rony`,
      },
    ],
  },
  {
    id: 18,
    name: "rony",
    age: 30,
    bloodGroup: "AB-",
    address: "Chandpur",
    phone: "016432735",
    lastDonad: 120,
    isMarriage: false,
    donatehistory: [
      {
        name: `khorshed`,
        name: `eman`,
        name: `aman`,
      },
    ],
  },
  {
    id: 19,
    name: "Kisor",
    age: 30,
    bloodGroup: "A+",
    address: "Kuyakata",
    phone: "016032735",
    lastDonad: 320,
    isMarriage: false,
    donatehistory: [
      {
        name: `forhad`,
        name: `akbar`,
        name: `akhi`,
      },
    ],
  },
  {
    id: 7,
    name: "jillur",
    age: 10,
    bloodGroup: "O+",
    address: "dinajpur",
    phone: "016432735",
    lastDonad: 120,
    isMarriage: false,
    donatehistory: [
      {
        name: `anamul`,
        name: `ahammad`,
        name: `ahadul`,
      },
    ],
  },
];
